// Mock data for demonstration purposes
export const MOCK_NOMADS = [
    {
        id: '1',
        name: 'Luna',
        age: 28,
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
        nomadType: 'Van Lifer',
        travelStyle: 'Slow Travel',
        currentLocation: 'Joshua Tree, CA',
        nextDestination: 'Sedona, AZ',
        leavingIn: 8,
        interests: ['Hiking', 'Yoga', 'Photography'],
        bio: 'Chasing sunsets and good coffee. 2 years on the road in my Sprinter.',
        isVerified: true,
    },
    {
        id: '2',
        name: 'Marcus',
        age: 32,
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        nomadType: 'Digital Nomad',
        travelStyle: 'Fast Paced',
        currentLocation: 'Tahoe, CA',
        nextDestination: 'Portland, OR',
        leavingIn: 3,
        interests: ['Skiing', 'Coding', 'Coffee'],
        bio: 'Remote engineer. Ski bum in winter, beach bum in summer.',
        isVerified: true,
    },
    {
        id: '3',
        name: 'Sophie',
        age: 26,
        avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400',
        nomadType: 'Backpacker',
        travelStyle: 'Seasonal',
        currentLocation: 'Moab, UT',
        nextDestination: 'Denver, CO',
        leavingIn: 14,
        interests: ['Climbing', 'Art', 'Live Music'],
        bio: 'Seasonal worker chasing adventures. Love a good campfire conversation.',
        isVerified: false,
    },
    {
        id: '4',
        name: 'Jake',
        age: 30,
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        nomadType: 'Overlander',
        travelStyle: 'Slow Travel',
        currentLocation: 'Big Sur, CA',
        nextDestination: 'Yosemite, CA',
        leavingIn: 5,
        interests: ['Surfing', 'MTB', 'Cooking'],
        bio: 'Living out of my 4Runner. Currently exploring the Pacific Coast.',
        isVerified: true,
    },
    {
        id: '5',
        name: 'Ava',
        age: 29,
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
        nomadType: 'Van Lifer',
        travelStyle: 'Slow Travel',
        currentLocation: 'Zion, UT',
        nextDestination: 'Grand Canyon, AZ',
        leavingIn: 10,
        interests: ['Hiking', 'Journaling', 'Stargazing'],
        bio: 'Minimalist life in a Promaster. Looking for hiking buddies.',
        isVerified: true,
    },
];
