export const MOCK_BUILDERS = [
    {
        id: '1',
        name: 'Chris',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
        skills: ['Electrical', 'Solar', 'Batteries'],
        yearsExperience: 8,
        hourlyRate: 75,
        bio: '8 years building vans. Specialized in off-grid solar systems.',
        rating: 4.9,
        reviews: 47,
        isVerified: true,
    },
    {
        id: '2',
        name: 'Sarah',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
        skills: ['Layout Design', 'Insulation', 'Woodwork'],
        yearsExperience: 5,
        hourlyRate: 60,
        bio: 'Interior designer turned van builder. Focus on space optimization.',
        rating: 4.8,
        reviews: 32,
        isVerified: true,
    },
    {
        id: '3',
        name: 'Mike',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
        skills: ['Plumbing', 'Water Systems', 'Heating'],
        yearsExperience: 12,
        hourlyRate: 85,
        bio: 'Former plumber. Expert in water and heating solutions for mobile living.',
        rating: 5.0,
        reviews: 63,
        isVerified: true,
    },
    {
        id: '4',
        name: 'Emily',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
        skills: ['Full Builds', 'Budget Planning', 'DIY Consulting'],
        yearsExperience: 4,
        hourlyRate: 50,
        bio: 'Built 3 vans myself. I help first-timers avoid common mistakes.',
        rating: 4.7,
        reviews: 28,
        isVerified: false,
    },
];
